language: node_js

node_js:
- 'node'

script:
  - npm run build

deploy:
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
  provider: pages
  skip-cleanup: true
